/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as AfterRouteImport } from './routes/after'
import { Route as AppRouteImport } from './routes/app'
import { Route as ExampleRouteImport } from './routes/example'
import { Route as FieldRouteImport } from './routes/field'
import { Route as FoundingRouteImport } from './routes/founding'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MethodRouteImport } from './routes/method'
import { Route as NotifyRouteImport } from './routes/notify'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WhoRouteImport } from './routes/who'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAfterRouteImport } from './routes/$locale/after'
import { Route as LocaleAppRouteImport } from './routes/$locale/app'
import { Route as LocaleExampleRouteImport } from './routes/$locale/example'
import { Route as LocaleFieldRouteImport } from './routes/$locale/field'
import { Route as LocaleFoundingRouteImport } from './routes/$locale/founding'
import { Route as LocaleGuidesRouteImport } from './routes/$locale/guides'
import { Route as LocaleLoginRouteImport } from './routes/$locale/login'
import { Route as LocaleMentionsLegalesRouteImport } from './routes/$locale/mentions-legales'
import { Route as LocaleMethodRouteImport } from './routes/$locale/method'
import { Route as LocaleNotifyRouteImport } from './routes/$locale/notify'
import { Route as LocalePrivacyRouteImport } from './routes/$locale/privacy'
import { Route as LocaleSourcesRouteImport } from './routes/$locale/sources'
import { Route as LocaleTermsRouteImport } from './routes/$locale/terms'
import { Route as LocaleWhoRouteImport } from './routes/$locale/who'
import { Route as CalendarTokenRouteImport } from './routes/calendar.$token'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as PassportTokenRouteImport } from './routes/passport.$token'
import { Route as PlansIndexRouteImport } from './routes/plans/index'
import { Route as PlansSlugRouteImport } from './routes/plans/$slug'
import { Route as LocaleGuidesIndexRouteImport } from './routes/$locale/guides/index'
import { Route as LocaleGuidesSlugRouteImport } from './routes/$locale/guides/$slug'
import { Route as LocalePassportTokenRouteImport } from './routes/$locale/passport.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPolarWebhookRouteImport } from './routes/api/polar/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AfterRoute = AfterRouteImport.update({
  id: '/after',
  path: '/after',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleRoute = ExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldRoute = FieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundingRoute = FoundingRouteImport.update({
  id: '/founding',
  path: '/founding',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifyRoute = NotifyRouteImport.update({
  id: '/notify',
  path: '/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoRoute = WhoRouteImport.update({
  id: '/who',
  path: '/who',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAfterRoute = LocaleAfterRouteImport.update({
  id: '/after',
  path: '/after',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAppRoute = LocaleAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleExampleRoute = LocaleExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFieldRoute = LocaleFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFoundingRoute = LocaleFoundingRouteImport.update({
  id: '/founding',
  path: '/founding',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleGuidesRoute = LocaleGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleMentionsLegalesRoute = LocaleMentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleMethodRoute = LocaleMethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleNotifyRoute = LocaleNotifyRouteImport.update({
  id: '/notify',
  path: '/notify',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSourcesRoute = LocaleSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleWhoRoute = LocaleWhoRouteImport.update({
  id: '/who',
  path: '/who',
  getParentRoute: () => LocaleRoute,
} as any)
const CalendarTokenRoute = CalendarTokenRouteImport.update({
  id: '/calendar/$token',
  path: '/calendar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const PassportTokenRoute = PassportTokenRouteImport.update({
  id: '/passport/$token',
  path: '/passport/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansSlugRoute = PlansSlugRouteImport.update({
  id: '/plans/$slug',
  path: '/plans/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleGuidesIndexRoute = LocaleGuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleGuidesRoute,
} as any)
const LocaleGuidesSlugRoute = LocaleGuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleGuidesRoute,
} as any)
const LocalePassportTokenRoute = LocalePassportTokenRouteImport.update({
  id: '/passport/$token',
  path: '/passport/$token',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolarWebhookRoute = ApiPolarWebhookRouteImport.update({
  id: '/api/polar/webhook',
  path: '/api/polar/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/after': typeof AfterRoute
  '/app': typeof AppRoute
  '/example': typeof ExampleRoute
  '/field': typeof FieldRoute
  '/founding': typeof FoundingRoute
  '/guides': typeof GuidesRouteWithChildren
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/method': typeof MethodRoute
  '/notify': typeof NotifyRoute
  '/owner': typeof OwnerRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
  '/who': typeof WhoRoute
  '/$locale/after': typeof LocaleAfterRoute
  '/$locale/app': typeof LocaleAppRoute
  '/$locale/example': typeof LocaleExampleRoute
  '/$locale/field': typeof LocaleFieldRoute
  '/$locale/founding': typeof LocaleFoundingRoute
  '/$locale/guides': typeof LocaleGuidesRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/mentions-legales': typeof LocaleMentionsLegalesRoute
  '/$locale/method': typeof LocaleMethodRoute
  '/$locale/notify': typeof LocaleNotifyRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/sources': typeof LocaleSourcesRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/who': typeof LocaleWhoRoute
  '/calendar/$token': typeof CalendarTokenRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/passport/$token': typeof PassportTokenRoute
  '/plans/$slug': typeof PlansSlugRoute
  '/$locale/': typeof LocaleIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/$locale/guides/$slug': typeof LocaleGuidesSlugRoute
  '/$locale/passport/$token': typeof LocalePassportTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/$locale/guides/': typeof LocaleGuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/after': typeof AfterRoute
  '/app': typeof AppRoute
  '/example': typeof ExampleRoute
  '/field': typeof FieldRoute
  '/founding': typeof FoundingRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/method': typeof MethodRoute
  '/notify': typeof NotifyRoute
  '/owner': typeof OwnerRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
  '/who': typeof WhoRoute
  '/$locale/after': typeof LocaleAfterRoute
  '/$locale/app': typeof LocaleAppRoute
  '/$locale/example': typeof LocaleExampleRoute
  '/$locale/field': typeof LocaleFieldRoute
  '/$locale/founding': typeof LocaleFoundingRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/mentions-legales': typeof LocaleMentionsLegalesRoute
  '/$locale/method': typeof LocaleMethodRoute
  '/$locale/notify': typeof LocaleNotifyRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/sources': typeof LocaleSourcesRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/who': typeof LocaleWhoRoute
  '/calendar/$token': typeof CalendarTokenRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/passport/$token': typeof PassportTokenRoute
  '/plans/$slug': typeof PlansSlugRoute
  '/$locale': typeof LocaleIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/plans': typeof PlansIndexRoute
  '/$locale/guides/$slug': typeof LocaleGuidesSlugRoute
  '/$locale/passport/$token': typeof LocalePassportTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/$locale/guides': typeof LocaleGuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/after': typeof AfterRoute
  '/app': typeof AppRoute
  '/example': typeof ExampleRoute
  '/field': typeof FieldRoute
  '/founding': typeof FoundingRoute
  '/guides': typeof GuidesRouteWithChildren
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/method': typeof MethodRoute
  '/notify': typeof NotifyRoute
  '/owner': typeof OwnerRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
  '/who': typeof WhoRoute
  '/$locale/after': typeof LocaleAfterRoute
  '/$locale/app': typeof LocaleAppRoute
  '/$locale/example': typeof LocaleExampleRoute
  '/$locale/field': typeof LocaleFieldRoute
  '/$locale/founding': typeof LocaleFoundingRoute
  '/$locale/guides': typeof LocaleGuidesRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/mentions-legales': typeof LocaleMentionsLegalesRoute
  '/$locale/method': typeof LocaleMethodRoute
  '/$locale/notify': typeof LocaleNotifyRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/sources': typeof LocaleSourcesRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/who': typeof LocaleWhoRoute
  '/calendar/$token': typeof CalendarTokenRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/passport/$token': typeof PassportTokenRoute
  '/plans/$slug': typeof PlansSlugRoute
  '/$locale/': typeof LocaleIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/$locale/guides/$slug': typeof LocaleGuidesSlugRoute
  '/$locale/passport/$token': typeof LocalePassportTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/$locale/guides/': typeof LocaleGuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/after'
    | '/app'
    | '/example'
    | '/field'
    | '/founding'
    | '/guides'
    | '/login'
    | '/mentions-legales'
    | '/method'
    | '/notify'
    | '/owner'
    | '/privacy'
    | '/sitemap.xml'
    | '/sources'
    | '/terms'
    | '/who'
    | '/$locale/after'
    | '/$locale/app'
    | '/$locale/example'
    | '/$locale/field'
    | '/$locale/founding'
    | '/$locale/guides'
    | '/$locale/login'
    | '/$locale/mentions-legales'
    | '/$locale/method'
    | '/$locale/notify'
    | '/$locale/privacy'
    | '/$locale/sources'
    | '/$locale/terms'
    | '/$locale/who'
    | '/calendar/$token'
    | '/guides/$slug'
    | '/passport/$token'
    | '/plans/$slug'
    | '/$locale/'
    | '/guides/'
    | '/plans/'
    | '/$locale/guides/$slug'
    | '/$locale/passport/$token'
    | '/api/auth/$'
    | '/api/polar/webhook'
    | '/$locale/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/after'
    | '/app'
    | '/example'
    | '/field'
    | '/founding'
    | '/login'
    | '/mentions-legales'
    | '/method'
    | '/notify'
    | '/owner'
    | '/privacy'
    | '/sitemap.xml'
    | '/sources'
    | '/terms'
    | '/who'
    | '/$locale/after'
    | '/$locale/app'
    | '/$locale/example'
    | '/$locale/field'
    | '/$locale/founding'
    | '/$locale/login'
    | '/$locale/mentions-legales'
    | '/$locale/method'
    | '/$locale/notify'
    | '/$locale/privacy'
    | '/$locale/sources'
    | '/$locale/terms'
    | '/$locale/who'
    | '/calendar/$token'
    | '/guides/$slug'
    | '/passport/$token'
    | '/plans/$slug'
    | '/$locale'
    | '/guides'
    | '/plans'
    | '/$locale/guides/$slug'
    | '/$locale/passport/$token'
    | '/api/auth/$'
    | '/api/polar/webhook'
    | '/$locale/guides'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/after'
    | '/app'
    | '/example'
    | '/field'
    | '/founding'
    | '/guides'
    | '/login'
    | '/mentions-legales'
    | '/method'
    | '/notify'
    | '/owner'
    | '/privacy'
    | '/sitemap.xml'
    | '/sources'
    | '/terms'
    | '/who'
    | '/$locale/after'
    | '/$locale/app'
    | '/$locale/example'
    | '/$locale/field'
    | '/$locale/founding'
    | '/$locale/guides'
    | '/$locale/login'
    | '/$locale/mentions-legales'
    | '/$locale/method'
    | '/$locale/notify'
    | '/$locale/privacy'
    | '/$locale/sources'
    | '/$locale/terms'
    | '/$locale/who'
    | '/calendar/$token'
    | '/guides/$slug'
    | '/passport/$token'
    | '/plans/$slug'
    | '/$locale/'
    | '/guides/'
    | '/plans/'
    | '/$locale/guides/$slug'
    | '/$locale/passport/$token'
    | '/api/auth/$'
    | '/api/polar/webhook'
    | '/$locale/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AfterRoute: typeof AfterRoute
  AppRoute: typeof AppRoute
  ExampleRoute: typeof ExampleRoute
  FieldRoute: typeof FieldRoute
  FoundingRoute: typeof FoundingRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MethodRoute: typeof MethodRoute
  NotifyRoute: typeof NotifyRoute
  OwnerRoute: typeof OwnerRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourcesRoute: typeof SourcesRoute
  TermsRoute: typeof TermsRoute
  WhoRoute: typeof WhoRoute
  CalendarTokenRoute: typeof CalendarTokenRoute
  PassportTokenRoute: typeof PassportTokenRoute
  PlansSlugRoute: typeof PlansSlugRoute
  PlansIndexRoute: typeof PlansIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPolarWebhookRoute: typeof ApiPolarWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/after': {
      id: '/after'
      path: '/after'
      fullPath: '/after'
      preLoaderRoute: typeof AfterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example': {
      id: '/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field': {
      id: '/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof FieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founding': {
      id: '/founding'
      path: '/founding'
      fullPath: '/founding'
      preLoaderRoute: typeof FoundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notify': {
      id: '/notify'
      path: '/notify'
      fullPath: '/notify'
      preLoaderRoute: typeof NotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who': {
      id: '/who'
      path: '/who'
      fullPath: '/who'
      preLoaderRoute: typeof WhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/after': {
      id: '/$locale/after'
      path: '/after'
      fullPath: '/$locale/after'
      preLoaderRoute: typeof LocaleAfterRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/app': {
      id: '/$locale/app'
      path: '/app'
      fullPath: '/$locale/app'
      preLoaderRoute: typeof LocaleAppRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/example': {
      id: '/$locale/example'
      path: '/example'
      fullPath: '/$locale/example'
      preLoaderRoute: typeof LocaleExampleRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/field': {
      id: '/$locale/field'
      path: '/field'
      fullPath: '/$locale/field'
      preLoaderRoute: typeof LocaleFieldRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/founding': {
      id: '/$locale/founding'
      path: '/founding'
      fullPath: '/$locale/founding'
      preLoaderRoute: typeof LocaleFoundingRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/guides': {
      id: '/$locale/guides'
      path: '/guides'
      fullPath: '/$locale/guides'
      preLoaderRoute: typeof LocaleGuidesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/mentions-legales': {
      id: '/$locale/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/$locale/mentions-legales'
      preLoaderRoute: typeof LocaleMentionsLegalesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/method': {
      id: '/$locale/method'
      path: '/method'
      fullPath: '/$locale/method'
      preLoaderRoute: typeof LocaleMethodRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/notify': {
      id: '/$locale/notify'
      path: '/notify'
      fullPath: '/$locale/notify'
      preLoaderRoute: typeof LocaleNotifyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/sources': {
      id: '/$locale/sources'
      path: '/sources'
      fullPath: '/$locale/sources'
      preLoaderRoute: typeof LocaleSourcesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/who': {
      id: '/$locale/who'
      path: '/who'
      fullPath: '/$locale/who'
      preLoaderRoute: typeof LocaleWhoRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/calendar/$token': {
      id: '/calendar/$token'
      path: '/calendar/$token'
      fullPath: '/calendar/$token'
      preLoaderRoute: typeof CalendarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/passport/$token': {
      id: '/passport/$token'
      path: '/passport/$token'
      fullPath: '/passport/$token'
      preLoaderRoute: typeof PassportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$slug': {
      id: '/plans/$slug'
      path: '/plans/$slug'
      fullPath: '/plans/$slug'
      preLoaderRoute: typeof PlansSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/guides/': {
      id: '/$locale/guides/'
      path: '/'
      fullPath: '/$locale/guides/'
      preLoaderRoute: typeof LocaleGuidesIndexRouteImport
      parentRoute: typeof LocaleGuidesRoute
    }
    '/$locale/guides/$slug': {
      id: '/$locale/guides/$slug'
      path: '/$slug'
      fullPath: '/$locale/guides/$slug'
      preLoaderRoute: typeof LocaleGuidesSlugRouteImport
      parentRoute: typeof LocaleGuidesRoute
    }
    '/$locale/passport/$token': {
      id: '/$locale/passport/$token'
      path: '/passport/$token'
      fullPath: '/$locale/passport/$token'
      preLoaderRoute: typeof LocalePassportTokenRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polar/webhook': {
      id: '/api/polar/webhook'
      path: '/api/polar/webhook'
      fullPath: '/api/polar/webhook'
      preLoaderRoute: typeof ApiPolarWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocaleGuidesRouteChildren {
  LocaleGuidesSlugRoute: typeof LocaleGuidesSlugRoute
  LocaleGuidesIndexRoute: typeof LocaleGuidesIndexRoute
}

const LocaleGuidesRouteChildren: LocaleGuidesRouteChildren = {
  LocaleGuidesSlugRoute: LocaleGuidesSlugRoute,
  LocaleGuidesIndexRoute: LocaleGuidesIndexRoute,
}

const LocaleGuidesRouteWithChildren = LocaleGuidesRoute._addFileChildren(
  LocaleGuidesRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAfterRoute: typeof LocaleAfterRoute
  LocaleAppRoute: typeof LocaleAppRoute
  LocaleExampleRoute: typeof LocaleExampleRoute
  LocaleFieldRoute: typeof LocaleFieldRoute
  LocaleFoundingRoute: typeof LocaleFoundingRoute
  LocaleGuidesRoute: typeof LocaleGuidesRouteWithChildren
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocaleMentionsLegalesRoute: typeof LocaleMentionsLegalesRoute
  LocaleMethodRoute: typeof LocaleMethodRoute
  LocaleNotifyRoute: typeof LocaleNotifyRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleSourcesRoute: typeof LocaleSourcesRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
  LocaleWhoRoute: typeof LocaleWhoRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocalePassportTokenRoute: typeof LocalePassportTokenRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAfterRoute: LocaleAfterRoute,
  LocaleAppRoute: LocaleAppRoute,
  LocaleExampleRoute: LocaleExampleRoute,
  LocaleFieldRoute: LocaleFieldRoute,
  LocaleFoundingRoute: LocaleFoundingRoute,
  LocaleGuidesRoute: LocaleGuidesRouteWithChildren,
  LocaleLoginRoute: LocaleLoginRoute,
  LocaleMentionsLegalesRoute: LocaleMentionsLegalesRoute,
  LocaleMethodRoute: LocaleMethodRoute,
  LocaleNotifyRoute: LocaleNotifyRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleSourcesRoute: LocaleSourcesRoute,
  LocaleTermsRoute: LocaleTermsRoute,
  LocaleWhoRoute: LocaleWhoRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocalePassportTokenRoute: LocalePassportTokenRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AfterRoute: AfterRoute,
  AppRoute: AppRoute,
  ExampleRoute: ExampleRoute,
  FieldRoute: FieldRoute,
  FoundingRoute: FoundingRoute,
  GuidesRoute: GuidesRouteWithChildren,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MethodRoute: MethodRoute,
  NotifyRoute: NotifyRoute,
  OwnerRoute: OwnerRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourcesRoute: SourcesRoute,
  TermsRoute: TermsRoute,
  WhoRoute: WhoRoute,
  CalendarTokenRoute: CalendarTokenRoute,
  PassportTokenRoute: PassportTokenRoute,
  PlansSlugRoute: PlansSlugRoute,
  PlansIndexRoute: PlansIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPolarWebhookRoute: ApiPolarWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
