/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as AppRouteImport } from './routes/app'
import { Route as FieldRouteImport } from './routes/field'
import { Route as FoundingRouteImport } from './routes/founding'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAppRouteImport } from './routes/$locale/app'
import { Route as LocaleFieldRouteImport } from './routes/$locale/field'
import { Route as LocaleFoundingRouteImport } from './routes/$locale/founding'
import { Route as LocaleGuidesRouteImport } from './routes/$locale/guides'
import { Route as LocaleLoginRouteImport } from './routes/$locale/login'
import { Route as LocalePrivacyRouteImport } from './routes/$locale/privacy'
import { Route as LocaleTermsRouteImport } from './routes/$locale/terms'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as PassportTokenRouteImport } from './routes/passport.$token'
import { Route as LocaleGuidesSlugRouteImport } from './routes/$locale/guides/$slug'
import { Route as LocalePassportTokenRouteImport } from './routes/$locale/passport.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPolarWebhookRouteImport } from './routes/api/polar/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldRoute = FieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundingRoute = FoundingRouteImport.update({
  id: '/founding',
  path: '/founding',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAppRoute = LocaleAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFieldRoute = LocaleFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFoundingRoute = LocaleFoundingRouteImport.update({
  id: '/founding',
  path: '/founding',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleGuidesRoute = LocaleGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LocaleRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const PassportTokenRoute = PassportTokenRouteImport.update({
  id: '/passport/$token',
  path: '/passport/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleGuidesSlugRoute = LocaleGuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleGuidesRoute,
} as any)
const LocalePassportTokenRoute = LocalePassportTokenRouteImport.update({
  id: '/passport/$token',
  path: '/passport/$token',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolarWebhookRoute = ApiPolarWebhookRouteImport.update({
  id: '/api/polar/webhook',
  path: '/api/polar/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/app': typeof AppRoute
  '/field': typeof FieldRoute
  '/founding': typeof FoundingRoute
  '/guides': typeof GuidesRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$locale/app': typeof LocaleAppRoute
  '/$locale/field': typeof LocaleFieldRoute
  '/$locale/founding': typeof LocaleFoundingRoute
  '/$locale/guides': typeof LocaleGuidesRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/passport/$token': typeof PassportTokenRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/guides/$slug': typeof LocaleGuidesSlugRoute
  '/$locale/passport/$token': typeof LocalePassportTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/field': typeof FieldRoute
  '/founding': typeof FoundingRoute
  '/guides': typeof GuidesRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$locale/app': typeof LocaleAppRoute
  '/$locale/field': typeof LocaleFieldRoute
  '/$locale/founding': typeof LocaleFoundingRoute
  '/$locale/guides': typeof LocaleGuidesRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/passport/$token': typeof PassportTokenRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/guides/$slug': typeof LocaleGuidesSlugRoute
  '/$locale/passport/$token': typeof LocalePassportTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/app': typeof AppRoute
  '/field': typeof FieldRoute
  '/founding': typeof FoundingRoute
  '/guides': typeof GuidesRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$locale/app': typeof LocaleAppRoute
  '/$locale/field': typeof LocaleFieldRoute
  '/$locale/founding': typeof LocaleFoundingRoute
  '/$locale/guides': typeof LocaleGuidesRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/passport/$token': typeof PassportTokenRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/guides/$slug': typeof LocaleGuidesSlugRoute
  '/$locale/passport/$token': typeof LocalePassportTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/app'
    | '/field'
    | '/founding'
    | '/guides'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/$locale/app'
    | '/$locale/field'
    | '/$locale/founding'
    | '/$locale/guides'
    | '/$locale/login'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/guides/$slug'
    | '/passport/$token'
    | '/$locale/'
    | '/$locale/guides/$slug'
    | '/$locale/passport/$token'
    | '/api/auth/$'
    | '/api/polar/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/field'
    | '/founding'
    | '/guides'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/$locale/app'
    | '/$locale/field'
    | '/$locale/founding'
    | '/$locale/guides'
    | '/$locale/login'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/guides/$slug'
    | '/passport/$token'
    | '/$locale'
    | '/$locale/guides/$slug'
    | '/$locale/passport/$token'
    | '/api/auth/$'
    | '/api/polar/webhook'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/app'
    | '/field'
    | '/founding'
    | '/guides'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/$locale/app'
    | '/$locale/field'
    | '/$locale/founding'
    | '/$locale/guides'
    | '/$locale/login'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/guides/$slug'
    | '/passport/$token'
    | '/$locale/'
    | '/$locale/guides/$slug'
    | '/$locale/passport/$token'
    | '/api/auth/$'
    | '/api/polar/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AppRoute: typeof AppRoute
  FieldRoute: typeof FieldRoute
  FoundingRoute: typeof FoundingRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  PassportTokenRoute: typeof PassportTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPolarWebhookRoute: typeof ApiPolarWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field': {
      id: '/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof FieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founding': {
      id: '/founding'
      path: '/founding'
      fullPath: '/founding'
      preLoaderRoute: typeof FoundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/app': {
      id: '/$locale/app'
      path: '/app'
      fullPath: '/$locale/app'
      preLoaderRoute: typeof LocaleAppRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/field': {
      id: '/$locale/field'
      path: '/field'
      fullPath: '/$locale/field'
      preLoaderRoute: typeof LocaleFieldRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/founding': {
      id: '/$locale/founding'
      path: '/founding'
      fullPath: '/$locale/founding'
      preLoaderRoute: typeof LocaleFoundingRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/guides': {
      id: '/$locale/guides'
      path: '/guides'
      fullPath: '/$locale/guides'
      preLoaderRoute: typeof LocaleGuidesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/passport/$token': {
      id: '/passport/$token'
      path: '/passport/$token'
      fullPath: '/passport/$token'
      preLoaderRoute: typeof PassportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/guides/$slug': {
      id: '/$locale/guides/$slug'
      path: '/$slug'
      fullPath: '/$locale/guides/$slug'
      preLoaderRoute: typeof LocaleGuidesSlugRouteImport
      parentRoute: typeof LocaleGuidesRoute
    }
    '/$locale/passport/$token': {
      id: '/$locale/passport/$token'
      path: '/passport/$token'
      fullPath: '/$locale/passport/$token'
      preLoaderRoute: typeof LocalePassportTokenRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polar/webhook': {
      id: '/api/polar/webhook'
      path: '/api/polar/webhook'
      fullPath: '/api/polar/webhook'
      preLoaderRoute: typeof ApiPolarWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocaleGuidesRouteChildren {
  LocaleGuidesSlugRoute: typeof LocaleGuidesSlugRoute
}

const LocaleGuidesRouteChildren: LocaleGuidesRouteChildren = {
  LocaleGuidesSlugRoute: LocaleGuidesSlugRoute,
}

const LocaleGuidesRouteWithChildren = LocaleGuidesRoute._addFileChildren(
  LocaleGuidesRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAppRoute: typeof LocaleAppRoute
  LocaleFieldRoute: typeof LocaleFieldRoute
  LocaleFoundingRoute: typeof LocaleFoundingRoute
  LocaleGuidesRoute: typeof LocaleGuidesRouteWithChildren
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocalePassportTokenRoute: typeof LocalePassportTokenRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAppRoute: LocaleAppRoute,
  LocaleFieldRoute: LocaleFieldRoute,
  LocaleFoundingRoute: LocaleFoundingRoute,
  LocaleGuidesRoute: LocaleGuidesRouteWithChildren,
  LocaleLoginRoute: LocaleLoginRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleTermsRoute: LocaleTermsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocalePassportTokenRoute: LocalePassportTokenRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AppRoute: AppRoute,
  FieldRoute: FieldRoute,
  FoundingRoute: FoundingRoute,
  GuidesRoute: GuidesRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  PassportTokenRoute: PassportTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPolarWebhookRoute: ApiPolarWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
